#!/usr/bin/env python3

import json
import os
import sys

# Paths
PROVIDERS_PATH = "~/.config/get/providers.json"

def error(message):
    print(message)
    exit(1)

def main():
    try:
        # Load the JSON data from providers.json
        data = open(os.path.expanduser(PROVIDERS_PATH)).read()
        providers = json.loads(data)

        if len(sys.argv) < 2:
            error("No provider specified.")

        provider = sys.argv[1]

        if not provider in providers:
            error("Unsupported provider '{}'.".format(provider))

        # Pass the remaining arguments to the provider
        arguments = sys.argv[2:]
        uri = providers[provider].format(*arguments)

        # Clone the repository at the evaluated URI
        os.system("git clone " + uri)
    except FileNotFoundError as e:
        error("Could not find " + PROVIDERS_PATH)
    except IndexError:
        error("Insufficient number of arguments.")

main()
